baseURL: https://talkix.flarex.io

jwt:
  issuer: identity.flarex.io
  audience: talkix.flarex.io
  jwksURL: https://identity.flarex.io/.well-known/jwks.json

line:
  messaging:
    channelToken: LINE_MESSAGING_API_TOKEN
    channelSecret: LINE_MESSAGING_API_SECRET
    webhookURL: https://talkix.flarex.io/webhook/line
  login:
    authURL: https://identity.flarex.io/auth/line

identity:
  serverURL: https://127.0.0.1:8443
  caFile: ca.crt
  certFile: client.crt
  keyFile: client.key

llm:
  model: openai:gpt-4.1-mini
  # prompt: replace with your prompt here
  summary:
    model: openai:gpt-4.1-mini
  line:
    model: openai:gpt-4.1
  persistence:
    driver: badger
    name: talkix
  tools:
    mcpServers:
      time:
        transport: stdio
        command: uvx
        args: [ "mcp-server-time", "--local-timezone=Asia/Taipei" ]
      google-maps:
        transport: stdio
        command: npx
        args: [ "-y", "@modelcontextprotocol/server-google-maps" ]
        env:
        - GOOGLE_MAPS_API_KEY=your_google_maps_api_key
    weather:
      # baseURL: https://api.openweathermap.org
      apiKey: WEATHER_API_KEY
      timeout: 10s
